name: "Deploy Avalonia App"
on:
  push:
    tags:
      - "Billing/v*"
    paths-ignore:
      - '*.md'

jobs:
  deploy-Linux:
    name: Linux Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ChannelName:
          - Release
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_NOLOGO: true
      BuildConfiguration: Release
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      GitHubReleaseUrl: https://github.com/avgra3/BillingLoggerApp/releases/download/Desktop-
      PROJECT_PATH: ./App.csproj

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use .NET Core SDK 6.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
          include-prerelease: false
      
      - name: Build, Tests, Cover, Pack and Publish (on push tag)
        shell: bash
        run: |
          dotnet tool install --global dotnet-releaser
          export PATH="$PATH:/root/.dotnet/tools"
          dotnet-releaser run --github-token "${{secrets.GITHUB_TOKEN}}" ./dotnet-releaser.toml